Create table user (id int generated by default as identity primary key,
					firstName varchar(45),
					lastName varchar(45),
					login varchar(45) unique,
					password varchar(45),
					email varchar(45) unique);