package db;

import entity.User;
import logic.UserDAO999;

import java.io.*;
import java.sql.*;
import java.util.Properties;

public class DBManager {
    private static Connection connection;
    private static DBManager dbManager;

    private DBManager() throws SQLException, IOException {
        connection = getConnection();
    }

    public static DBManager getInstance() throws SQLException, IOException {
        if (dbManager == null) dbManager = new DBManager();
        return dbManager;
    }

    public Connection getConnection() throws SQLException, IOException {
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        File file = new File("C:\\Users\\Admin\\Desktop\\BeautySalon\\src\\main\\resources\\app.properties");
        FileInputStream in = new FileInputStream(file);
        Properties properties = new Properties();
        properties.load(in);

        String url = properties.getProperty("connection.url");
        String username = properties.getProperty("username");
        String password = properties.getProperty("password");
        return DriverManager.getConnection(url, username, password);
    }


    public void insertUser(User user) throws SQLException {
        Statement stm = null;
        PreparedStatement pst;
        try {
            stm = connection.createStatement();
            String SQLCheckName ="Select ID from users where name=?";
            pst= connection.prepareStatement(SQLCheckName);
            ResultSet rs= pst.executeQuery();
            rs.next();

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        } finally {
            assert stm != null;
            stm.close();
        }
    }
//
//    public void CreateTableUsers() throws SQLException {
//        Statement stm = null;
//        try {
//            String SQLCreateTableUsers = "CREATE TABLE users (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name VARCHAR(45) UNIQUE,password VARCHAR(80))";
//            stm = connection.createStatement();
//            stm.executeUpdate(SQLCreateTableUsers);
//        } catch (SQLException throwables) {
//            throwables.printStackTrace();
//        } finally {
//            assert stm != null;
//            stm.close();
//        }
//    }
//
//    public void ClearTableUsers() throws SQLException {
//        Statement stm = null;
//        try {
//            stm = connection.createStatement();
//            String SQLTruncateTable = "TRUNCATE TABLE users CASCADE";
//            stm.executeUpdate(SQLTruncateTable);
//        } catch (SQLException throwables) {
//            throwables.printStackTrace();
//        } finally {
//            assert stm != null;
//            stm.close();
//        }
//    }
//
//    public void ShowAllUsers() throws SQLException {
//        PreparedStatement pstm = null;
//        ResultSet rs = null;
//        try {
//            String SQLSHowAllUsers = "SELECT * FROM users";
//            pstm = connection.prepareStatement(SQLSHowAllUsers);
//            rs = pstm.executeQuery();
//            while (rs.next()) {
//                String id = rs.getString(1);
//                String name = rs.getString(2);
//                String password = rs.getString(3);
//                System.out.println(id + " " + name + " " + password);
//            }
//
//        } catch (SQLException throwables) {
//            throwables.printStackTrace();
//        } finally {
//            assert pstm != null;
//            pstm.close();
//            assert rs != null;
//            rs.close();
//        }
//    }
//
//    public boolean CheckUserName(String name) throws SQLException {
//        PreparedStatement pstm = null;
//        ResultSet rs = null;
//        try {
//            String SQLSHowAllUsers = "SELECT * FROM users";
//            pstm = connection.prepareStatement(SQLSHowAllUsers);
//            rs = pstm.executeQuery();
//            while (rs.next()) {
//                String name1 = rs.getString(2);
//                if (name.equals(name1)){
//                    return true;
//                }
//            }
//
//        } catch (SQLException throwables) {
//            throwables.printStackTrace();
//        } finally {
//            assert pstm != null;
//            pstm.close();
//            assert rs != null;
//            rs.close();
//        }
//        return false;
//    }
}
